# This is a basic workflow to help you get started with Actions

name: Simple workflow

on:
# Controls when the workflow will run
  issues:
    types:
      -opened 
jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Create
      id: Create
      uses: atlassian/gajira-create@v3
      with:
        project: IODP
        issuetype: Bug
        summary: Issue created by ${{ github.actor }} with the title ${{ github.event.issue.title }} on GitHub repository ${{ github.repository }} 
        description: URL to issue- ${{ github.event.issue.html_url }} Issue Summary- ${{ github.event.issue.body }}
        
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
